In [1]:
import pandas as pd
import numpy as np

In [7]:
import pyandev
from pyandev.tests import data as test_data

In [3]:
pyandev.__version__

'0.1.0'

In [4]:
dir(pyandev)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version',
 'data_summary',
 'data_values_summary',
 'discretisation',
 'plot',
 'tests']

In [8]:
boston_df = test_data.load_boston_df(insert_missings = True)

In [9]:
boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target
0,0.00632,18.0,NaN,0.0,0.538,NaN,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,NaN,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,NaN,NaN,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,NaN,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,NaN,2.94,33.4
4,0.06905,0.0,2.18,NaN,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,NaN,36.2

In [10]:
pyandev.data_values_summary.data_values_summary(boston_df)

,CRIM_value,CRIM_count,ZN_value,ZN_count,INDUS_value,INDUS_count,CHAS_value,CHAS_count,NOX_value,NOX_count,...,TAX_value,TAX_count,PTRATIO_value,PTRATIO_count,B_value,B_count,LSTAT_value,LSTAT_count,target_value,target_count
0,0.00632,1,0.0,331,0.46,1,0.0,416,0.385,1,...,187.0,1,12.6,3,0.32,1,1.73,1,5.0,2
1,0.00906,1,12.5,9,0.74,1,1.0,34,0.389,1,...,188.0,5,13.0,11,2.52,1,1.92,1,5.6,1
2,0.01096,1,17.5,1,1.21,1,NaN,56,0.392,2,...,193.0,7,13.6,1,2.60,1,1.98,1,6.3,1
3,0.01301,1,18.0,1,1.22,1,NaN,None,0.394,1,...,198.0,1,14.4,1,3.50,1,2.47,1,7.0,2
4,0.01311,1,20.0,19,1.25,2,NaN,None,0.398,2,...,216.0,5,14.7,32,3.65,1,2.87,1,7.2,3
5,NaN,None,21.0,2,NaN,None,NaN,None,NaN,None,...,NaN,None,14.8,3,NaN,None,NaN,None,NaN,None
6,0.24980,1,22.0,9,4.15,1,NaN,None,0.488,6,...,287.0,7,14.9,4,385.41,1,11.64,1,21.5,2
7,0.25199,1,25.0,10,4.39,2,NaN,None,0.489,14,...,289.0,5,15.1,1,385.64,1,11.65,1,21.6,2
8,0.25356,1,28.0,3,4.49,4,NaN,None,0.493,7,...,293.0,3,15.2,9,385.76,1,11.66,1,21.7,7
9,0.25387,1,30.0,6,4.86,4,NaN,None,0.499,4,...,296.0,8,15.3,3,385.81,1,11.72,1,21.8,2
10,0.25915,1,33.0,2,4.93,6,NaN,None,0.504,8,...,300.0,6,15.5,1,385.91,1,11.97,1,21.9,3
11,0.26363,1,34.0,2,4.95,2,NaN,None,0.507,8,...,304.0,14,15.6,2,385.96,1,11.98,1,22.0,7
12,NaN,None,35.0,3,NaN,None,NaN,None,NaN,None,...,NaN,None,15.9,1,NaN,None,NaN,None,NaN,None
13,51.13580,1,40.0,6,19.58,29,NaN,None,0.718,6,...,437.0,14,16.0,5,396.30,1,34.37,1,46.7,1
14,67.92080,1,45.0,6,21.89,12,NaN,None,0.740,9,...,469.0,1,16.1,4,396.33,1,34.41,1,48.3,1
15,73.53410,1,52.5,1,25.65,7,NaN,None,0.770,7,...,666.0,120,16.4,6,396.42,1,36.98,1,48.5,1
16,88.97620,1,55.0,3,27.74,5,NaN,None,0.871,14,...,711.0,5,16.6,16,396.90,109,37.97,1,48.8,1
17,NaN,46,60.0,4,NaN,39,NaN,None,NaN,59,...,NaN,41,16.8,4,NaN,50,NaN,61,50.0,16
18,NaN,None,70.0,3,NaN,None,NaN,None,NaN,None,...,NaN,None,16.9,5,NaN,None,NaN,None,NaN,None
19,NaN,None,75.0,3,NaN,None,NaN,None,NaN,None,...,NaN,None,17.0,4,NaN,None,NaN,None,NaN,None
20,NaN,None,80.0,14,NaN,None,NaN,None,NaN,None,...,NaN,None,17.3,1,NaN,None,NaN,None,NaN,None
21,NaN,None,82.5,2,NaN,None,NaN,None,NaN,None,...,NaN,None,17.4,16,NaN,None,NaN,None,NaN,None
22,NaN,None,85.0,2,NaN,None,NaN,None,NaN,None,...,NaN,None,17.6,6,NaN,None,NaN,None,NaN,None
23,NaN,None,90.0,5,NaN,None,NaN,None,NaN,None,...,NaN,None,17.8,21,NaN,None,NaN,None,NaN,None
24,NaN,None,95.0,3,NaN,None,NaN,None,NaN,None,...,NaN,None,17.9,9,NaN,None,NaN,None,NaN,None
25,NaN,None,100.0,1,NaN,None,NaN,None,NaN,None,...,NaN,None,18.0,5,NaN,None,NaN,None,NaN,None
26,NaN,None,NaN,55,NaN,None,NaN,None,NaN,None,...,NaN,None,18.2,4,NaN,None,NaN,None,NaN,None
27,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.3,4,NaN,None,NaN,None,NaN,None
28,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.4,13,NaN,None,NaN,None,NaN,None
29,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.5,3,NaN,None,NaN,None,NaN,None
30,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.6,16,NaN,None,NaN,None,NaN,None
31,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.7,9,NaN,None,NaN,None,NaN,None
32,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.8,2,NaN,None,NaN,None,NaN,None
33,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,18.9,2,NaN,None,NaN,None,NaN,None
34,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,19.0,4,NaN,None,NaN,None,NaN,None
35,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,19.1,16,NaN,None,NaN,None,NaN,None
36,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,19.2,15,NaN,None,NaN,None,NaN,None
37,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,19.6,6,NaN,None,NaN,None,NaN,None
38,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,19.7,8,NaN,None,NaN,None,NaN,None
39,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,20.1,5,NaN,None,NaN,None,NaN,None
40,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,20.2,118,NaN,None,NaN,None,NaN,None
41,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,20.9,9,NaN,None,NaN,None,NaN,None
42,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,21.0,24,NaN,None,NaN,None,NaN,None
43,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,21.1,1,NaN,None,NaN,None,NaN,None
44,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,21.2,14,NaN,None,NaN,None,NaN,None
45,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,22.0,1,NaN,None,NaN,None,NaN,None
46,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,NaN,58,NaN,None,NaN,None,NaN,None
47,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None
48,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None
49,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,...,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None